# Generated by Django 3.1.6 on 2021-02-18 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=200)),
                ('instructorName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='courseDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selfLearnigCouse', models.CharField(max_length=500)),
                ('instructorBasedCourse', models.CharField(max_length=500)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DemoWebapp.allcourses')),
            ],
        ),
    ]
